Glusk/sveder

checkstyle.xml, src/main/java/com/github/glusk2/sveder/Ordinacija.java, src/main/java/com/github/glusk2/sveder/excel/ExcelOrdinacije.java, src/main/java/com/github/glusk2/sveder/excel/NumericnaCelica.java, src/test/java/com/github/glusk2/sveder/excel/TestExcelOrdinacije.java
=> #7 Premaknjena koda za num. vrednost celic.

.travis.yml, README.md
=> #13 Dodana Travis CI konfiguracija

.gitattributes, src/test/java/com/github/glusk/sveder/excel/TestExcelOrdinacije.java
=> #21 Introduce end-of-line normalization

README.md
=> #25 Dodana motivacija

README.md
=> #27 Popravljena struktura

README.md
=> #27 Dodaj dejavnost

pom.xml
=> #34 Dodan pluginManagement

pom.xml
=> #36 Dodan javadoc plugin

README.md, release.sh
=> #15 Dodana release skripta

src/main/java/com/github/glusk/sveder/iskanje/package-info.java
=> #42 Dopolnjena dokumentacija paketa

README.md, src/main/java/com/github/glusk/sveder/Dejavnost.java, src/main/java/com/github/glusk/sveder/Ordinacija.java, src/main/java/com/github/glusk/sveder/excel/ExcelOrdinacije.java, src/main/java/com/github/glusk/sveder/iskanje/OrdinacijeImeDejavnost.java, src/test/java/com/github/glusk/sveder/SvederIT.java
=> #43 Dodan enum Dejavnost

src/main/java/com/github/glusk/sveder/Dejavnost.java, src/main/java/com/github/glusk/sveder/excel/ExcelOrdinacije.java, src/test/java/com/github/glusk/sveder/excel/TestExcelOrdinacije.java
=> #43 Popravek enuma Dejavnost

src/main/java/com/github/glusk/sveder/excel/ExcelOrdinacije.java
=> #45 Popravljen opis konstruktorja

src/main/java/com/github/glusk/sveder/excel/package-info.java
=> #52 Popravek dokumentacije paketa

README.md
=> #54 Popravek strukture v README.md

pom.xml, src/test/java/com/github/glusk/sveder/SvederIT.java, src/test/java/com/github/glusk/sveder/excel/TestExcelOrdinacije.java, src/test/java/com/github/glusk/sveder/excel/TestIzvajalec.java, src/test/java/com/github/glusk/sveder/excel/TestZdravstveniZavod.java, src/test/java/com/github/glusk/sveder/net/TestUrlNaStrani.java
=> #58 Preklop na JUnit5

src/main/java/com/github/glusk/sveder/excel/ZdravstveniZavod.java, src/test/java/com/github/glusk/sveder/excel/TestZdravstveniZavod.java
=> #57 Popravek napake; dodan test

src/main/java/com/github/glusk/sveder/excel/Izvajalec.java, src/test/java/com/github/glusk/sveder/excel/TestIzvajalec.java
=> #62 Popravek napake; dodan test

src/main/java/com/github/glusk/sveder/Urnik.java, src/main/java/com/github/glusk/sveder/excel/ExcelUrnik.java, src/main/java/com/github/glusk/sveder/excel/Izvajalec.java, src/main/java/com/github/glusk/sveder/excel/KljucLokacijeOrdinacije.java, src/main/java/com/github/glusk/sveder/excel/KljucOrdinacije.java, src/main/java/com/github/glusk/sveder/excel/LokacijeZdravstvenihZavodov.java, src/main/java/com/github/glusk/sveder/excel/VrsticaUrnika.java
=> #66 Popravljeni Javadoc komentarji

.travis.yml
=> #51 Izvede integracijski test na Travis CI

src/main/java/com/github/glusk/sveder/net/SpletnaStran.java, src/main/java/com/github/glusk/sveder/net/UrlNaStrani.java, src/test/java/com/github/glusk/sveder/net/TestUrlNaStrani.java
=> #70 Popravek UrlNaStrani in dodan test

src/main/java/com/github/glusk/sveder/excel/ExcelOrdinacije.java, src/main/java/com/github/glusk/sveder/excel/Izvajalec.java, src/main/java/com/github/glusk/sveder/excel/ZdravstveniZavod.java, src/main/java/com/github/glusk/sveder/net/SvederUrl.java, src/test/java/com/github/glusk/sveder/excel/TestIzvajalec.java, src/test/java/com/github/glusk/sveder/excel/TestZdravstveniZavod.java, src/test/java/com/github/glusk/sveder/net/TestUrlNaStrani.java
=> #46 Odstranjen razred UrlOvoj

src/main/java/com/github/glusk/sveder/SifraLokacijeIzvajalca.java, src/test/java/com/github/glusk/sveder/TestSifraLokacijeIzvajalca.java
=> #90 Popravljena sifra lokacije

src/main/java/com/github/glusk/sveder/excel/ExcelOrdinacije.java
=> #3 Logika popravljena
